### PR TITLE
Fixed two typos and removed a math error

### PR DESCRIPTION
**Pull request by TalKachman**
The way U3 is defined there is no imaginary part  I in the Pauli matrix $\sigma_x$

### CODE REVIEW

**Comment by rraymondhp** [comment]
Hi Tal, 
Thanks. But I think the U3 is defined with the imaginary part as in the openqasm paper. 
Please refer to the Equation 2 in this paper: https://arxiv.org/pdf/1707.03429.pdf

So you should not remove the "i" there.

**Comment by rraymondhp** [comment]
Can I close this?

**Comment by TalKachman** [comment]
Done

**Comment by rraymondhp** [comment]
@TalKachman  
Thanks for the quick fix. However, it seems that you are editing an old file. Can you do edition on this file instead: https://github.com/jaygambetta/qiskit-tutorial/blob/71cd8712b3699083c8757b3df13d140cc6b45503/reference/tools/quantum_gates_and_linear_algebra.ipynb

**Comment by jaygambetta** [comment]
@rraymondhp what is the status of this pr should we just close.

**Comment by rraymondhp** [comment]
Yes, please close it. I will ask Tal to review the new version we have later.

**Pull request closed without merging**
